version: '3'
services:
  node-app:
    build:
      target: production
      context: .
      args:
       NODE_ENV: production
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis 

